accum_grad: 1
cmvn: global_cmvn
cmvn_conf:
  cmvn_file: data/train/global_cmvn
  is_json_cmvn: true
cmvn_file: data\train\global_cmvn
dataset_conf:
  batch_conf:
    batch_type: dynamic
    max_frames_in_batch: 30000
  fbank_conf:
    dither: 0.0
    frame_length: 25
    frame_shift: 10
    num_mel_bins: 80
  feats_type: fbank
  filter_conf:
    max_length: 4096
    min_length: 10
    token_max_length: 200
    token_min_length: 0
  mfcc_conf:
    dither: 0.1
    frame_length: 25
    frame_shift: 10
    high_freq: -400
    low_freq: 20
    num_ceps: 40
  resample_conf:
    resample_rate: 16000
  shuffle: true
  shuffle_conf:
    shuffle_size: 1500
  sort: true
  sort_conf:
    sort_size: 500
  spec_aug: true
  spec_aug_conf:
    max_f: 10
    max_t: 50
    num_f_mask: 2
    num_t_mask: 2
  speed_perturb: false
decoder: null
encoder: null
grad_clip: 5
input_dim: 80
is_json_cmvn: true
lfmmi_dir: ''
log_interval: 50
max_epoch: 100
optim: adam
optim_conf:
  lr: 0.001
output_dim: 5
scheduler: warmuplr
scheduler_conf:
  warmup_steps: 1000
sed: true
stutternet: true
